# 处理大型数组的计算
- 问题：对大型的数据集比如数组或网格（grid）进行计算
- 解决：使用numpy库
- [numpy官方链接](http://www.numpy.org)

** 对于任何涉及数组的计算密集型任务，使用numpy库 **

numpy的主要特性是为python提供了数组对象，比python标准库中的列表有更好的性能表现，更加适合于做数学计算

## 比较列表和numpy中的数组不同之处

In [1]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [3]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
import numpy as np

In [5]:
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])

In [6]:
ax + 2

array([3, 4, 5, 6])

In [7]:
ax + 10

array([11, 12, 13, 14])

In [8]:
ax + ay

array([ 6,  8, 10, 12])

In [9]:
ax * ay

array([ 5, 12, 21, 32])

可以看到numpy中的array在进行标量运算时是针对逐个元素进行计算的，当两个操作数都是数组时，会针对相对应的元素进行计算，产生出一个新数组作为结果。

** <span class="mark">由于所有的数学操作会施加在所有元素上，使得对整个数组的计算变得非常简单和快速</span> **

## 计算多项式的值

In [10]:
def f(x):
    return 3*x**2 - 2*x +7

In [11]:
f(ax)

array([ 8, 15, 28, 47])

## numpy提供了一些通用函数对数组进行操作，替代了math模块中对应的函数

In [12]:
np.sqrt(ax)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [13]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

** 使用numpy中的通用函数效率要比对数组进行迭代然后使用math模块中的函数每次只处理一个元素快上百倍，因此有可能就要使用这些通用函数**

## numpy数组底层

在底层，numpy数组的内存分配方式和C一样。即它们是大块连续内存，由同一种类型的数据组成。因此，numpy可以创建比python中的列表大得多的数组。

### 创建一个10000* 10000的二维浮点数组

In [14]:
grid = np.zeros(shape=(10000, 10000), dtype=float)
grid

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

所有的常用操作仍然额可以同时施加于所有元素之上

In [15]:
grid += 10
grid

array([[ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       ..., 
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.]])

In [16]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ..., 
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

## numpy扩展了python列表的索引功能（多维数组）

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10 , 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

选出第二行

In [18]:
a[1]

array([5, 6, 7, 8])

选出第二列

In [19]:
a[:, 1]

array([ 2,  6, 10])

选出子区域，并进行相应操作

In [20]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [21]:
a[1:3, 1:3] += 10

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

一个向量作用于所有行

In [23]:
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

条件赋值一个数组

In [25]:
np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

Python中大量的科学和工程类函数库都以numpy作为基础，它也是广泛使用中最为庞大和复杂的模块之一

最常见的导入方式是``` import numpy as np```