# 矩阵和线性代数的运算
- 执行矩阵和线性代数方面的操作，比如矩阵乘法、求行列式、解线性方程

## Matrix对象和3.9中的数组对象相似，但是计算的时候遵循线性代数规则。

In [1]:
import numpy as np

In [2]:
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8 ,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

## 转置矩阵

In [3]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

## 逆矩阵

In [4]:
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [5]:
m * m.I

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
        [ -2.22044605e-16,   0.00000000e+00,   1.00000000e+00]])

## 创建一个向量并和矩阵相乘

In [6]:
vector = np.matrix([[2], [3], [4]])
vector

matrix([[2],
        [3],
        [4]])

In [7]:
m * vector

matrix([[ 8],
        [32],
        [ 2]])

## 更多的线性代数操作可在numpy.linalg

In [8]:
import numpy.linalg

### 行列式

In [9]:
numpy.linalg.det(m)

-229.99999999999983

### 特征值

In [10]:
x = numpy.linalg.eigvals(m)
x

array([-13.11474312,   2.75956154,   6.35518158])

### 求mx = vector 的解

In [11]:
x = numpy.linalg.solve(m, vector)
x

matrix([[ 0.96521739],
        [ 0.17391304],
        [ 0.46086957]])

In [12]:
m * x

matrix([[ 2.],
        [ 3.],
        [ 4.]])

In [13]:
vector

matrix([[2],
        [3],
        [4]])

numpy可以处理线性代数的问题。更多参考 http://www.numpy.org