# Numpy小技巧和注意点

## list转换为numpy的array

In [1]:
import numpy as np
list_temp = [[1,2,3],[4,5,6]]
list_temp = np.array(list_temp)
list_temp

array([[1, 2, 3],
       [4, 5, 6]])

** <span class="mark">当lsit中各个元素的维度不一样的时候，array并不能将其解释为数组类型，而是一个object类型</span> **

In [2]:
list_temp = [[1,2,3],[4,5]]
list_temp = np.array(list_temp)
list_temp

array([list([1, 2, 3]), list([4, 5])], dtype=object)

列表中元素是np的array仍然可以直接拼接成新的array

In [3]:
list_temp = [np.array([1, 2, 3]), np.array([4, 5, 6])]
list_temp = np.array(list_temp)
list_temp

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2 = np.array([np.arange(3), np.arange(3)])
arr2

array([[0, 1, 2],
       [0, 1, 2]])